// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppMenuBar: typeof import('./src/components/app/AppMenuBar.vue')['default']
    Calculator: typeof import('./src/components/calculator/Calculator.vue')['default']
    CalculatorItem: typeof import('./src/components/calculator/CalculatorItem.vue')['default']
    Counter: typeof import('./src/components/Counter.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    MaterialTable: typeof import('./src/components/calculator/MaterialTable.vue')['default']
    PrimeButton: typeof import('primevue/button')['default']
    PrimeCard: typeof import('primevue/card')['default']
    PrimeCheckbox: typeof import('primevue/checkbox')['default']
    PrimeColumn: typeof import('primevue/column')['default']
    PrimeDataTable: typeof import('primevue/datatable')['default']
    PrimeDropdown: typeof import('primevue/dropdown')['default']
    PrimeFieldset: typeof import('primevue/fieldset')['default']
    PrimeInputNumber: typeof import('primevue/inputnumber')['default']
    PrimeMenubar: typeof import('primevue/menubar')['default']
  }
}

export { }
